# Generated by Django 4.0.5 on 2022-08-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_bundle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bundle',
            new_name='Mixed',
        ),
    ]
